name: BiliBili Daily Task

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'

env:
  ASPNETCORE_ENVIRONMENT: Production
  Ray_BiliBiliCookies__1: ${{ secrets.COOKIE }}
  Ray_BiliBiliCookies__2: ${{ secrets.COOKIE2 }}
  Ray_BiliBiliCookies__3: ${{ secrets.COOKIE3 }}
  Ray_RunTasks: Daily
  Ray_DailyTaskConfig__NumberOfCoins: ${{ secrets.NUMBER_OF_COINS }}
  Ray_DailyTaskConfig__SelectLike: 'true'
  Ray_DailyTaskConfig__SaveCoinsWhenLv6: 'false'
  Ray_DailyTaskConfig__DayOfReceiveVipPrivilege: '1'
  Ray_DailyTaskConfig__DayOfExchangeSilver2Coin: '-1'
  Ray_Security__RandomSleepMaxMin: '20'
  Ray_Serilog__WriteTo__0__Args__restrictedToMinimumLevel: Information

jobs:
  daily-task:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Set time zone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Run Daily Task
        run: |
          cd ./src/Ray.BiliBiliTool.Console
          dotnet run -c Release --runTasks=Daily
