name: BiliBili Live Lottery

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11,19 * * *'

env:
  ASPNETCORE_ENVIRONMENT: Production
  HUSKY: 0
  Ray_BiliBiliCookies__1: ${{ secrets.COOKIE }}
  Ray_BiliBiliCookies__2: ${{ secrets.COOKIE2 }}
  Ray_BiliBiliCookies__3: ${{ secrets.COOKIE3 }}
  Ray_RunTasks: LiveLottery
  Ray_Security__RandomSleepMaxMin: '10'
  Ray_Serilog__WriteTo__0__Args__restrictedToMinimumLevel: Information

jobs:
  live-lottery:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Set time zone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      - name: Random Sleep (5-30 minutes)
        run: |
          SLEEP_TIME=$(( RANDOM % 1560 + 300 ))
          echo "Sleeping for $((SLEEP_TIME/60)) minutes and $((SLEEP_TIME%60)) seconds..."
          sleep $SLEEP_TIME

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Run Live Lottery Task
        run: |
          cd ./src/Ray.BiliBiliTool.Console
          dotnet run -c Release --runTasks=LiveLottery
